spring:
  # MySQL Sever Properties
  # Running externally in-order to keep the same database for everyone's progress
  # Secured via a forced SSL certificate authentication
  # Was unable to use absolute file path, so hosted externally on https://henrikoci.co.uk/certs/keystore.jks for now.
  datasource:
    url: >
      jdbc:mysql://ddns.henrikoci.co.uk:8888/fitify?
      useSSL=true&
      requireSSL=true&
      clientCertificateKeyStoreUrl=https://henrikoci.co.uk/certs/keystore.jks&
      clientCertificateKeyStoreType=JKS&
      clientCertificateKeyStorePassword=Gr0UpS3v3NS3cr3t
    username: Cv6QJrdcFY
    password: FTe5tzsUhgc5RBhSQgqgsZq736NGAM4DzKCqbKn5AfnAnxVL2cKmfsMyyBuUjUS9wzw2sQeX5ndKqCy5eYZEFESgd5nWQ2tbaKJ
  # Default Spring Boot database connection test query
  dbcp2:
    max-wait-millis: 30000
    validation-query: "SELECT 1"
    validation-query-timeout: 30
  # Spring JPA properties
  # Using hibernation update to change the database values when the schema is changed
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
# SpringDoc is the documentation service, we are using Swagger-ui via OpenAPI3 (Spring)
springdoc:
  pathsToMatch: /api/**, /authenticate
# The Jason Web Token secret used in hashing algorithm for passwords by Spring Security
jwt:
  secret: 09955BD2DE87

