# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend (React)

# This workflow is triggered when there are push changes to the node.js source code
on:
  push:
    paths:
    - '**.js'

# Set the default directory to the front-end code at the backend folder
defaults:
  run:
    working-directory: src/frontend-react

# Performs the following workflow
jobs:
  build:
    # Start a Ubuntu VM
    runs-on: ubuntu-latest
    
    # Specify only Node.js version 14 to be used as CI
    strategy:
      matrix:
        node-version: [14.x]

    # The processes to run on the VM
    steps:
    - uses: actions/checkout@v2 # Checkout git
    - name: Use Node.js ${{ matrix.node-version }} # Setup node with the appropriate node version.
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci # Install node project in a clean state (removed modules so they are recompiled)
    - run: npm run build --if-present # Build Node.js project
    - run: npm test # Run the Node.js project under test mode
