# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend (React)

# This workflow is triggered when there are push changes to the node.js source code
on:
  push:
    paths:
    - '**.jsx'

# Set the default directory to the front-end code at the backend folder
defaults:
  run:
    working-directory: src/frontend-react

# Performs the following workflow
jobs:
  build:
    # Start a Ubuntu VM
    runs-on: ubuntu-latest

    # The processes to run on the VM
    steps:
    - uses: actions/checkout@v2 # Checkout git
    - name: Use Node.js 14.x # Setup node with the appropriate node version.
      uses: actions/setup-node@v1
      with:
        node-version: '14.x' # Specify only the Node.js version 14 to be used as this is what we are developing with.
    - run: npm ci # Install node project in a clean state (removed modules so they are recompiled), for CI testing - this fails the build if warnings are detected
    - run: npm run build --if-present # Build Node.js project
    - run: npm test --passWithNoTests # Run the Node.js project under test mode, enable no errors if no tests are present
